user:
  username: Tom
  password: 123456
  age: 23

person:
  - username: Tom
    password: 123456
    age: 21
  - username: Jack
    password: 1234
    age: 2

employee:
  person:
    - username: Tom
      password: 123456
      age: 21
    - username: Jack
      password: 1234
      age: 2